stages:
  - deques
  - autocomplete
  - minpq
  - seamfinding

workflow:
  auto_cancel:
    on_job_failure: none

ArrayListDequeTests:
  stage: deques
  rules:
    - changes:
        - src/main/java/deques/*.java
  script: ./gradlew --warning-mode=all test --tests "deques.ArrayListDequeTests"
  when: always

ArrayDequeTests:
  stage: deques
  rules:
    - changes:
        - src/main/java/deques/*.java
  script: ./gradlew --warning-mode=all test --tests "deques.ArrayDequeTests"
  when: always

LinkedDequeTests:
  stage: deques
  rules:
    - changes:
        - src/main/java/deques/*.java
  script: ./gradlew --warning-mode=all test --tests "deques.LinkedDequeTests"
  when: always

TreeSetAutocompleteTests:
  stage: autocomplete
  rules:
    - changes:
        - src/main/java/autocomplete/*.java
  script: ./gradlew --warning-mode=all test --tests "autocomplete.TreeSetAutocompleteTests"
  when: always

SequentialSearchAutocompleteTests:
  stage: autocomplete
  rules:
    - changes:
        - src/main/java/autocomplete/*.java
  script: ./gradlew --warning-mode=all test --tests "autocomplete.SequentialSearchAutocompleteTests"
  when: always

BinarySearchAutocompleteTests:
  stage: autocomplete
  rules:
    - changes:
        - src/main/java/autocomplete/*.java
  script: ./gradlew --warning-mode=all test --tests "autocomplete.BinarySearchAutocompleteTests"
  when: always

TernarySearchTreeAutocompleteTests:
  stage: autocomplete
  rules:
    - changes:
        - src/main/java/autocomplete/*.java
  script: ./gradlew --warning-mode=all test --tests "autocomplete.TernarySearchTreeAutocompleteTests"
  when: always

DoubleMapMinPQTests:
  stage: minpq
  rules:
    - changes:
        - src/main/java/minpq/*.java
  script: ./gradlew --warning-mode=all test --tests "minpq.DoubleMapMinPQTests"
  when: always

UnsortedArrayMinPQTests:
  stage: minpq
  rules:
    - changes:
        - src/main/java/minpq/*.java
  script: ./gradlew --warning-mode=all test --tests "minpq.UnsortedArrayMinPQTests"
  when: always

HeapMinPQTests:
  stage: minpq
  rules:
    - changes:
        - src/main/java/minpq/*.java
  script: ./gradlew --warning-mode=all test --tests "minpq.HeapMinPQTests"
  when: always

OptimizedHeapMinPQTests:
  stage: minpq
  rules:
    - changes:
        - src/main/java/minpq/*.java
  script: ./gradlew --warning-mode=all test --tests "minpq.OptimizedHeapMinPQTests"
  when: always

AdjacencyListSeamFinderTests:
  stage: seamfinding
  rules:
    - changes:
        - src/main/java/graphs/**/*.java
        - src/main/java/seamfinding/**/*.java
  script: ./gradlew --warning-mode=all test --tests "seamfinding.AdjacencyListSeamFinderTests"
  when: always

GenerativeSeamFinderTests:
  stage: seamfinding
  rules:
    - changes:
        - src/main/java/graphs/**/*.java
        - src/main/java/seamfinding/**/*.java
  script: ./gradlew --warning-mode=all test --tests "seamfinding.GenerativeSeamFinderTests"
  when: always

DynamicProgrammingSeamFinderTests:
  stage: seamfinding
  rules:
    - changes:
        - src/main/java/graphs/**/*.java
        - src/main/java/seamfinding/**/*.java
  script: ./gradlew --warning-mode=all test --tests "seamfinding.DynamicProgrammingSeamFinderTests"
  when: always